[build-system]
requires = ["setuptools >= 59.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">= 3.10"
name = "spycilab"
version = "0.1.0"
description = "A tool for building complex GitLab pipelines."
